name: 'Bilibili Selfcharging'

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 23 1,16 * *'
    
jobs:
  Bilibili_Selfcharging:
    runs-on: ubuntu-20.04
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2
      - name: 'Set python'
        uses: actions/setup-python@v1
        with:
          python-version: '3.9.21'
      - name: 'Install dependencies'
        run: python -m pip install --upgrade -r requirements.txt
      - name: 'Start Selfcharging'
        env:
          LOGIN_API_URL: ${{ secrets.LOGIN_API_URL }}
          OCR_TOKEN: ${{ secrets.OCR_TOKEN }}
          OCR_URL: ${{ secrets.OCR_URL }}
          UP_MID: ${{ secrets.UP_MID }}
          PHONE_LIST: ${{ secrets.PHONE_LIST }}
          Z15821506118_USERNAME: ${{ secrets.Z15821506118_USERNAME }}
          Z15821506118_PASSWORD: ${{ secrets.Z15821506118_PASSWORD }}
        run: python main.py
      - name: Append Success Log #追加成功日志
        run: |
          echo "$(date +%Y-%m-%d\ %H:%M:%S) - 完成操作" >> run.log
      - name: Upload log #上传日志
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: run.log
      - name: Push log #更新日志
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: auto-checkin
          branch: main
